<?php

$pDbConnection         = "connect.php";
$pSharedFunctions      = "shared_functions.php";
$pIndexLogic           = "index_logic.php";
$pHome                 = "index.php"; //
$pSignInView           = "index.php"; // chyba warto to zmienic
$pSignUpView           = "index.php"; // 
$pSignInLogic          = "sign_in_logic.php";
$pLogout               = "logout.php";
$pSignUpValidation     = "sign_up_logic.php";
$pAdminPanel           = "admin_panel.php";
$pUsersList            = "users_list.php";
$pUsersEdit            = "users_edit.php";
$pUsersEditValidation  = "users_edit_validation.php";
$pUsersDelete          = "users_delete.php";
$pUsersActivate        = "users_activate.php";
$pUsersOrders          = "users_orders.php";
$pUsersOrdersCancel    = "users_orders_cancel.php";
$pUsersOrdersConfirm   = "users_orders_confirm.php";
$pMenuEdit             = "menu_edit.php";
$pMenuDelete           = "menu_delete.php";
$pMenuAdd              = "menu_add.php";
$pMenuEditValidation   = "menu_edit_validation.php";
$pMenu                 = "menu.php";
$pMenuAddValidation    = "menu_add_validation.php";
$pEmployeePanel        = "employee_panel.php";
$pEmployeePanelConfirm = "employee_panel_confirm.php";
$pEmployeePanelCancel  = "employee_panel_cancel.php";
$pOrders               = "orders.php";
$pOrdersAdd            = "orders_add.php";
$pOrderAdd             = "order_add.php";
$pOrderDelete          = "order_delete.php";